* Работа с сокетами

** UDP сокет

http://www.erlang.org/doc/man/gen_udp.html

Запустим 2 ноды, и пообщаемся по UDP между ними.

На 1й ноде откроем UDP на порту 2000:
#+BEGIN_SRC Erlang
1> {ok, Socket} = gen_udp:open(2000, [binary, {active, true}]).
{ok,#Port<0.587>}
#+END_SRC

На 2й ноде откроем UDP на порту 2001:
#+BEGIN_SRC Erlang
1> {ok, Socket} = gen_udp:open(2001, [binary, {active, true}]).
{ok,#Port<0.587>}
#+END_SRC

Пошлем сообщение с 1-й на 2-ю ноду:
#+BEGIN_SRC Erlang
2> gen_udp:send(Socket, {127,0,0,1}, 2001, <<"Hello from 2000">>).
ok
#+END_SRC

На второй ноде убедимся, что сообщение пришло. И пошлем ответ:
#+BEGIN_SRC Erlang
2> flush().
Shell got {udp,#Port<0.587>,{127,0,0,1},2000,<<"Hello from 2000">>}
ok
3> gen_udp:send(Socket, {127,0,0,1}, 2000, <<"Hello from 2001">>).
ok
#+END_SRC

На первой убедимся, что сообщение пришло:
#+BEGIN_SRC Erlang
3> flush().
Shell got {udp,#Port<0.587>,{127,0,0,1},2001,<<"Hello from 2001">>}
ok
#+END_SRC


** Активный и пассивный режим сокета

И gen_udp, и gen_tcp, оба имеют одну важную настройку: режим работы с входящими данными.

Это может быть либо активный режим {active, true}, либо пассивный режим {active, false}.

В активном режиме входящие пакеты отправляются сообщениями потоку -- владельцу сокета.
И поток должен их получить с помощью receive и обработать.

Для udp сокета это сообщения вида:
{udp, Socket, IP, InPortNo, Packet}
мы их уже видели:
{udp,#Port<0.587>,{127,0,0,1},2001,<<"Hello from 2001">>}

Для tcp сокета аналогичные сообщения:
{tcp, Socket, Packet}

Активный режим прост в использовании, но опасен тем, что клиент может
завалить сообщениями поток и нарушить его работу. То есть, открывает возможности
для DDOS атак. Поэтому рекомендуется пассивный режим.

В пассивном режиме данные нужно забрать самому, вызовом
gen_udp:recv/3, gen_tcp:recv/3

#+BEGIN_SRC Erlang
gen_udp:recv(Socket, Length, Timeout) ->
        {ok, {Address, Port, Packet}} | {error, Reason}

gen_tcp:recv(Socket, Length, Timeout) -> {ok, Packet} | {error, Reason}
#+END_SRC

Здесь мы указываем, сколько байт данных хотим прочитать из сокета. Если там есть
эти данные, то мы получаем их сразу. Если нет, то вызов блокируется, пока не
придет достаточное к-во данных. Можно указать Timeout, чтобы не блокироваться навечно :)

Еще есть вариант {active, once}. В этом случае сокет запускается в активном режиме,
получает первый пакет данных как сообщение, и сразу переключается в пассивный режим.


** TCP сокет

http://www.erlang.org/doc/man/gen_tcp.html

наивная реализация
src/tcp_socket.erl


** Ranch Acceptor Pool

http://yzh44yzh.by/post/ranch.html
