* Создать папки

* Перекинуть материалы по другим папкам
** docs/01_base в 01_t_erlang_base
** loop_process пересмотреть, переместить в 04_p_gen_server
** base перекинуть в 07_p_eunit
** testing пересмотреть, переместить в 07_p_eunit
** http_server пересмотреть, переместить в 08_p_cowboy
** naive_tcp_server в 10_p_sockets
** distributed_chat пересмотреть, переместить в 15_p_distribution
** смержить
key_value_storage/
key_value_storage_2/
переместить в 11_p_key_value_storage

** rec2plist -- вообще удалить

* Подготовить темы:

** 01_t_erlang_base
   подготовить конспект
   можно взять что-то из doc/01_base

** 02_t_concurrency
   подготовить конспект

** 03_t_otp
   подготовить конспект

** 04_p_gen_server
   подготовить конспект
   пересмотреть код, переделать, если надо
   там хорошо бы монитор ставить, ближе к otp реализации

** 05_t_tools
   подготовить конспект

** 06_t_libs
   подготовить конспект

** 07_p_eunit
   подготовить конспект
   подготовить код
   старого кода много, нужно его переосмыслить. Идею тестирования на нескольких уровнять сохранить
   пару слов и про common test надо бы

** 08_p_cowboy
   подготовить конспект
   подготовить код
   старый код есть, но вряд ли полезный. Тут лучше все заново подготовить
   плюс еще веб-сокет нужен

** 09_p_node
   подготовить конспект
   подготовить код

** 10_p_sockets
   подготовить конспект
   подготовить код
   старый код есть, полезный. Пересмотреть его

** 11_p_key_value_storage
   подготовить конспект
   подготовить код
   тут две версии старого кода, нужно мержить в одну. И, наверное, не доделано все по фичам.
