* Анализ проведенного курса, пересмотр тем.

** 01_t
слишком большая, разбить на 2-3 темы.
Из них одна или две -- практика. Хорошо пошли рекурсивные функции с аккумуляторами как практика.
Можно что-то еще. lists:flatten
для foldl, foldr нужны хорошие примеры, а то суммировать и умножить все элементы списка -- это отстой

1 час 20 минут -- до KV структур данных
50 минут до List Comprehention. нужно больше хороших примеров.
10 минут остальное. binary раскрыл плохо, нужно больше примеров.
Итого 3 часа 20 минут.
Можно взять 4 часа на все эти темы.

Про мапы тож нужно рассказывать.

** 02_t
30m ну я спешил, можно было подробнее. Оставим время 1 час

** 03_t
25м. Аналогично, спешил. Нужен 1 час.

** 04_p
практика по ген-сервер, сделали за 1 час 40 мин, планировалось 2 часа. Тут ок.

Таймаут (5й этап) незачем выносить в отдельный этап, сделали как часть 3-го этапа.
Для демонстрации monitor нужно сделать ошибку в серверном процессе.
Сделал 100/0, это фигня. Нужно придумать более реалистичный пример.

** 05_t
слишком большая тема, нужно разбивать на части

Rebar - 30m -- сделать отдельной темой
использовал свою презентацию -- удобно, нужны презентации по всем темам.

Логирование - 30м -- сделать отдельной темой

observer, webtools - 10m
можно добавить что-то еще.

tracing 30 минут -- нужно отдельной темой, и с практикой

dialyzer 20 минут -- нужно подробнее про типы, больше примеров, лучше примеры.
тут я анализировал только src, нужно уметь анализировать и beam тоже
знать, в чем разница
А, и как правильно сделать --build_plt, какие там приложения нужно подключить


** 06_t
libs планировался 1 час, рассказал за 20 минут.
тут сделать материал на 30 минут, и будет ок.

** 07_t
eunit практика
планировался 1 час, сделали за 45 минут

глубже раскрыть тему, я не про все фичи рассказал.
setup/teardown
у Фреда есть глава
добавить работы, пусть будет 1 час

** 08_p
cowboy
планировал 2 часа, делали 2 часа 20 минут, не успели и половины.
сделали: static, http_handler, session_manager

большая и сложная тема, потянет часа на 4, не меньше.

нужно разбить на 2 практики:
- статика и http хендлеры
- веб-сокеты (и тут использовать JSON, а не примитивный текстовый протокол)

и нужно заранее заготовить и раздать студентам:
js, css, img/sample.jpg, index.html
может еще какие-то снипеты кода
а то набирать весь static с нуля вручную прямо на занятии бесперспективно

NOTE: библиотека сессий для ковбоя нужна народу :)
поискать готовые решения или сделать свое



** 09_p
развертывание и запуск ноды
пропустил эту тему
и не нужно делать отдельной темой, это будет часть практики 11_p


** 10_p
сокеты
планировалась как практика, провел теоретически, боялся не успеть с основной практикой
ничего, успели. Надо и это проводить как практику.

планировался 1 час, рассказал за 40 мин.

udp все попробовали в консоли, в обоих режимах в активном и пассивном.


** 11_p
кодовую базу взять ~/tmp/ctidb, там хорошо получилось
старый код, от 1-го курса, пересмотреть, может чего-то добавить оттуда в новый.

db.erl, unit test, dialyzer - 1h 10m
flash to file, read from file, settings - 1h 10m
production/test mode - 20m
tcp api - 55m
http api - 35m (помогло вчерашнее занятие по cowboy)
упаковка, deploy - 1h 20m
итого, все сделали за 5h 30m

Были непонятные моменты:
на application:stop не вызвается gen_server:terminate
отправка сообщения ген-серверу из stop уже не работает, но работает из prep_stop
не пишутся в лог и на консоль ошибки, которые возникают после application:stop
Ну то есть, просто сделать flush_to_file из gen_server:terminate не помогает.
Тогда как сделать это правильно?

нужен скрипт для запуска и остановки ноды.
Аналогично, как в tvzavr, только нужно открытое решение.



* сделать презетнации со слайдами по всем темам
в каждой теме, теоритической и практической, должен быть org-черновик
и odp презентация










* линки для черновиков
http://yzh44yzh.by/post/rebar.html
http://yzh44yzh.by/post/dialyzer.html
http://yzh44yzh.by/post/trace_dbg.html
http://yzh44yzh.by/post/erlang_for_web_2.html
http://yzh44yzh.by/post/distributed_erlang.html


* в перспективе можно сделать видеокурс
